version: '3.8'

services:
  app:
    image: laravelsail/php83-composer
    container_name: noctis-app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    ports:
      - 8000:8000
    tty: true
